import { NextRequest, NextResponse } from 'next/server';
import { esService } from '@/lib/server/services/elasticsearch/client';
import { ES_INDICES } from '@/lib/server/config/elasticsearch';

export const dynamic = 'force-dynamic';

export async function POST(req: NextRequest) {
  try {
    const { complaint_id, escalation_level = 'department_head', additional_context = '' } = await req.json();
    if (!complaint_id) {
      return NextResponse.json({ success: false, error: 'complaint_id is required' }, { status: 400 });
    }

    const complaint = await esService.get<any>(ES_INDICES.CIVIC_EVENTS, complaint_id);
    if (!complaint) {
      return NextResponse.json({ success: false, error: 'Complaint not found' }, { status: 404 });
    }

    const escalationTargets: Record<string, { title: string; office: string }> = {
      department_head: { title: 'Commissioner', office: `${complaint.department} Head Office` },
      mayor: { title: "Hon'ble Mayor", office: 'BBMP Office, Bengaluru' },
      mla: { title: "Hon'ble MLA", office: `${complaint.ward_name} Constituency` },
      lokayukta: { title: 'Karnataka Lokayukta', office: 'Lokayukta Bhavan, Bengaluru' },
    };

    const target = escalationTargets[escalation_level] || escalationTargets.department_head;
    const today = new Date().toLocaleDateString('en-IN');

    const escalationLetter = {
      type: 'ESCALATION_LETTER',
      complaint_id,
      escalation_level,
      generated_at: new Date().toISOString(),
      content: `
═══════════════════════════════════════════════════════════════════════════════
                         ESCALATION LETTER
═══════════════════════════════════════════════════════════════════════════════

Date: ${today}

To,
${target.title},
${target.office}

Subject: Escalation of Unresolved Complaint - ${complaint_id}

Respected Sir/Madam,

I am writing to escalate complaint ${complaint_id}, which has remained unresolved for ${complaint.days_open} days despite multiple follow-ups.

COMPLAINT DETAILS:
─────────────────
- Complaint ID: ${complaint_id}
- Filed On: ${complaint.created_at?.split('T')[0]}
- Department: ${complaint.department}
- Ward: ${complaint.ward_name}
- Category: ${complaint.category}
- Current Status: ${complaint.status}
- Days Pending: ${complaint.days_open}
- Previous Escalations: ${complaint.escalation_count || 0}

ISSUE SUMMARY:
─────────────
${complaint.description}

REASON FOR ESCALATION:
─────────────────────
The complaint has been pending for ${complaint.days_open} days, exceeding the standard SLA of 7 days. Despite ${complaint.escalation_count || 0} previous escalation(s), no satisfactory resolution has been provided.

${additional_context ? `\nADDITIONAL CONTEXT:\n${additional_context}\n` : ''}

REQUESTED ACTION:
────────────────
1. Immediate attention to resolve this complaint
2. Written explanation for the delay
3. Action against officials responsible for negligence
4. Compensation for inconvenience caused (if applicable)

I request your urgent intervention to ensure resolution within 7 days.

Thanking you,

[CITIZEN NAME]
[CONTACT DETAILS]

CC:
- Chief Secretary, Government of Karnataka
- Bengaluru Development Minister
- Local Corporator

═══════════════════════════════════════════════════════════════════════════════
Generated by GhostOffice Platform
═══════════════════════════════════════════════════════════════════════════════
      `.trim(),
      metadata: {
        target,
        complaint_summary: {
          id: complaint_id,
          days_open: complaint.days_open,
          department: complaint.department,
          status: complaint.status,
        },
      },
    };

    return NextResponse.json({ success: true, data: escalationLetter });
  } catch (error: any) {
    console.error('Error generating escalation:', error);
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}
